[package]
name = "hello_world_rust"
version = "0.1.0"
authors = ["mouldy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
rand = "0.5.5"
